Repository payara/Payara-Server-Documentation, pull requests merged in 2018-03, with the labels that each got.

#301 Big PR for Typo Fixes
  documentation/payara-micro/deploying/deploy-cmd-line.adoc
  documentation/payara-micro/stopping-instance.adoc
  documentation/payara-server/password-aliases/password-aliases-overview.adoc
  general-info/general-info.adoc
  images/password-aliases/password-aliases-unused.png
  images/password-aliases/password-aliases-using.png
  release-notes/README.adoc
Labels: payara4

#314 PYSVC-748 postdeploycommandfile and variable refs in Py Micro
  documentation/payara-micro/asadmin/pre-and-post-boot-scripts.adoc
  images/payara-micro/uber-jar-command-scripts-structure.png
Labels: payara4

#311 PYSVC-664 Note about tech preview
  documentation/microprofile/config.adoc
Labels: payara4

#326 PYSVC-593
  documentation/payara-server/app-deployment/app-deployment.adoc
Labels: payara4

#328 Batch fix PR for 4.181
  documentation/microprofile/README.adoc
Labels: payara4

#332 PAYARA-2460 Initial documentation for MP JWT-Auth
  SUMMARY.adoc
  documentation/microprofile/README.adoc
  documentation/microprofile/jwt.adoc
  documentation/payara-server/app-deployment/deployment-descriptors.adoc
  documentation/payara-server/app-deployment/descriptor-elements.adoc
Labels: payara4

#336 PYSVC-755 Request Tracing Overhaul
  documentation/payara-server/request-tracing-service/asadmin-commands.adoc
  documentation/payara-server/request-tracing-service/configuration.adoc
  documentation/payara-server/request-tracing-service/request-tracing-service.adoc
  images/request-tracing/configuration-admin-console.png
Labels: payara5

#335 PYSVC-740
  build-instructions/build-instructions.adoc
  general-info/supported-platforms.adoc
Labels: payara5

#333 PYSVC-692 Document HTTP/2 Configuration
  SUMMARY.adoc
  documentation/payara-server/server-configuration/http/README.adoc
  documentation/payara-server/server-configuration/http/network-listeners.adoc
  documentation/payara-server/server-configuration/http/protocols.adoc
  documentation/payara-server/server-configuration/http/virtual-servers.adoc
  images/http/network-listener-config.png
  images/http/protocol-config.png
  images/http/virtual-server-config.png
  images/virtual-servers/left-bar-location.png
Labels: payara5

#331 PYSVC-753 Document Clustered Singleton
  SUMMARY.adoc
  documentation/payara-server/public-api/README.adoc
  documentation/payara-server/public-api/cdi-events.adoc
  documentation/payara-server/public-api/clustered-singleton.adoc
Labels: payara5

#329 PYSVC-590 Changed configuration elements in deployment descriptors
  documentation/payara-server/app-deployment/deployment-descriptors.adoc
  documentation/payara-server/app-deployment/descriptor-elements.adoc
Labels: payara5

#325 PYSVC-746 Add clustermode documentation for Micro
  documentation/payara-micro/adding-jars.adoc
  documentation/payara-micro/appendices/cmd-line-opts.adoc
  documentation/payara-micro/clustering/autoclustering.adoc
  documentation/payara-micro/clustering/clustering-with-full-server.adoc
Labels: payara5

#324 PYSVC-696 Update documentation to include Domain Data Grid docs.
  SUMMARY.adoc
  documentation/payara-server/hazelcast/asadmin.adoc
  documentation/payara-server/hazelcast/concept.adoc
  documentation/payara-server/hazelcast/configuration.adoc
  documentation/payara-server/hazelcast/discovery.adoc
  documentation/payara-server/hazelcast/enable-hazelcast.adoc
  documentation/payara-server/hazelcast/using-hazelcast.adoc
  documentation/payara-server/hazelcast/viewing-members.adoc
  images/domain-datagrid/discovery-mode.png
  images/hazelcast/hazelcast-admin-console-availability-enable-ejb-persistence.png
  images/hazelcast/hazelcast-admin-console-availability-enable-web-persistence.png
  images/hazelcast/hazelcast-admin-console-config-hazelcast-options.png
  images/hazelcast/hazelcast-admin-console-domain-hazelcast-options.png
  images/hazelcast/hazelcast-admin-console-enable-hazelcast.png
  images/hazelcast/hazelcast-admin-console-select-availability-service.png
  images/hazelcast/hazelcast-admin-console-select-instance-config.png
  images/hazelcast/hazelcast-admin-console-set-configuration-file.png
  images/hazelcast/hazelcast-admin-console-view-cluster-members-from-domain.png
Labels: payara5

#312 PYSVC-689 Added docs for Micro Arquillian container.
  SUMMARY.adoc
  documentation/ecosystem/arquillian-containers/README.adoc
  documentation/ecosystem/arquillian-containers/payara-micro.adoc
  documentation/ecosystem/cloud-connectors/README.adoc
  documentation/ecosystem/ecosystem.adoc
Labels: ecosystem, payara5

#316 PYSVC-695 First cut documentation for deployment groups
  SUMMARY.adoc
  documentation/payara-server/asadmin-commands/asadmin-commands.adoc
  documentation/payara-server/deployment-groups/README.adoc
  documentation/payara-server/deployment-groups/asadmin-commands.adoc
  images/deployment-groups/add-server-to-dg.png
  images/deployment-groups/delete-deployment-group.png
  images/deployment-groups/deploy-to-dg.png
  images/deployment-groups/deployment-group-new.png
  images/deployment-groups/lifecycle-dg.png
  images/deployment-groups/remove-server-from-dg.png
Labels: payara5

#317 PYSVC-747 Data Grid EJB Timer persistence
  documentation/payara-server/ejb.adoc
  images/ejb/set-ejb-timer-persistence.png
Labels: payara5, post-merge-review

#322 PYSVC-698 Document embedded H2 database
  SUMMARY.adoc
  documentation/payara-server/h2/h2.adoc
  documentation/payara-server/jbatch/database-support.adoc
  documentation/payara-server/jbatch/schema-name.adoc
Labels: payara5, post-merge-review

#323 PYSCV 687 Document replacement of Derby with H2 in Payara Micro
  SUMMARY.adoc
  documentation/payara-micro/h2/h2.adoc
Labels: payara5, post-merge-review

#327 PYSVC-691 Updated Production Domain Information.
  documentation/payara-server/production-ready-domain.adoc
Labels: payara5

#330 PYSVC-679 Renaming "payaradomain" to "production"
  documentation/payara-server/app-deployment/app-deployment.adoc
  documentation/payara-server/asadmin-commands/server-management-commands.adoc
  documentation/payara-server/production-ready-domain.adoc
Labels: payara5

#334 PYSVC-685 Ansi colours used by default from 5.181
  documentation/payara-server/logging/ansi-colours.adoc
Labels: payara5

#338 PAYARA-2615 documentation for the --sslCert command line switch intro…
  documentation/payara-micro/appendices/cmd-line-opts.adoc
  documentation/payara-micro/configuring/config-keystores.adoc
  documentation/payara-micro/configuring/config-sys-props.adoc
Labels: payara4, payara5
